spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.28.132
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
